// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiNGT1wgA2YMzuB5qaAPhS3d9pMz0BR0s',
    appId: '1:488544937930:android:2e65457e2509457d785133',
    messagingSenderId: '488544937930',
    projectId: 'fatora-6859a',
    storageBucket: 'fatora-6859a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0bxUSe9mzv5d1hf4sDgUyI1ynDffB2m8',
    appId: '1:488544937930:ios:1fd157fe17915993785133',
    messagingSenderId: '488544937930',
    projectId: 'fatora-6859a',
    storageBucket: 'fatora-6859a.firebasestorage.app',
    androidClientId: '488544937930-s3fni2hdu3388h56p63085ec3m2pp06g.apps.googleusercontent.com',
    iosClientId: '488544937930-f0qp2h8m0oh5jeumbr1fvo7qtb0mq52q.apps.googleusercontent.com',
    iosBundleId: 'com.example.fatora',
  );
}
